### PR TITLE
Adds Condition to Intellihide Windows if in Primary Monitor

### PR DESCRIPTION
**Pull request by HideyoshiNakazone**
Adds the condition where intellihide will only interfere if the window is in the primary monitor (were the Top Bar is located).

This is not a major merge request and only adds a small feature and a code method, this is my first public merge request to a open source project. Any feedback is welcome.

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thanks for your contribution!

Does this fix any bugs or other type of undesired behavior?

**Comment by HideyoshiNakazone** [comment]
When you have a multi-monitor setup and there's a window in the secondary monitor in the top intellihide hides the top bar even when there's nothing in the primary monitor where the top bar is. This merge request fixes this.

**Comment by tuxor1337** [comment]
Hm, but this should never happen, because the monitor index is checked already:
https://github.com/tuxor1337/hidetopbar/blob/49e91bcd84dff746ea4d7939cdc6a95142bdd72b/intellihide.js#L232

I suspect that there rather is a problem with that `this._monitorIndex` value getting out of sync when a monitor is added or removed.

**Comment by tuxor1337** [comment]
My guess is that the primary monitor's index is read only once at the beginning, when the extension is loaded, and after that, any later changes to the monitor setup will not be passed on to the `PanelVisibilityManager` and to `Intellihide`:
https://github.com/tuxor1337/hidetopbar/blob/49e91bcd84dff746ea4d7939cdc6a95142bdd72b/extension.js#L34-L39
A proper fix would be a way to update the `monitorIndex` whenever the monitor setup changes, probably here:
https://github.com/tuxor1337/hidetopbar/blob/49e91bcd84dff746ea4d7939cdc6a95142bdd72b/panelVisibilityManager.js#L436-L443

**Pull request closed without merging**
