### PR TITLE
Fix top bar getting stuck on GNOME 42

### LINKED ISSUE #354: GNOME 42: Top panel stuck open
If the cursor leaves the panel without immediately touching the desktop (e.g. it could go directly on top of an overlapping window), the `leave-event` signal doesn't fire and the panel will be stuck.

https://user-images.githubusercontent.com/67334567/159691713-a9dbd294-2b89-4924-8e70-279f81527ca5.mp4

### PR DESCRIPTION
**Pull request by jdoe0000000**
On GNOME 42, leave-event doesn't fire if the mouse cursor doesn't touch the desktop immediately after leaving the panel, which causes the panel to be stuck. Fix this by listening to changes to the has-pointer property of the panel and all of its visible children instead.

Fixes #354.

### CODE REVIEW

**Comment by tuxor1337** [comment]
Is this fix backwards compatible?

**Comment by tuxor1337** [comment]
I tested it on GNOME 40.9 and backwards compatibility should be fine there, but the panel will hide in the overview even when the "Show panel in overview" setting is activated. This can be fixed using this patch:
```diff
diff --git a/panelVisibilityManager.js b/panelVisibilityManager.js
index c73a089..e923e6d 100644
--- a/panelVisibilityManager.js
+++ b/panelVisibilityManager.js
@@ -365,6 +365,7 @@ var PanelVisibilityManager = class HideTopBar_PanelVisibilityManager {
                 'showing',
                 () => {
                     if(this._showInOverview) {
+                        this._preventHide = true;
                         this.show(
                             this._settings.get_double('animation-time-overview'),
                             "showing-overview"
@@ -376,6 +377,7 @@ var PanelVisibilityManager = class HideTopBar_PanelVisibilityManager {
                 Main.overview,
                 'hiding',
                 () => {
+                    this._updatePreventHide();
                     this.hide(
                         this._settings.get_double('animation-time-overview'),
                         "hiding-overview"
```
Would you please integrate this fix and verify that it still works on you setup? Furthermore, it would be good to know whether this is going to break compatibility with 3.38 before releasing it...

**Comment by jdoe0000000** [comment]
>Is this fix backwards compatible?

I checked that all the APIs I used are available at least as far back as GNOME 3.38, but I didn't actually try using the extension on older GNOME versions.

>I tested it on GNOME 40.9 and backwards compatibility should be fine there, but the panel will hide in the overview even when the "Show panel in overview" setting is activated. This can be fixed using this patch:

Thanks for the patch. Unfortunately, it doesn't seem to work correctly on GNOME 42; the panel becomes stuck after going to the overview.

**Comment by tuxor1337** [comment]
Okay, that's tricky. I have been testing it on GNOME 40.9 for several hours now with the patch and it works fine. So, there's really a subtle difference between 40 and 42 also in the handling of the overview... Unfortunately, I currently don't have time to set up a GNOME 42 environment for testing.

**Comment by jacksongoode** [comment]
I can also test this and get back to you!

**Comment by gnome-mpv** [comment]
I found that the original approach doesn't work properly with extensions that add their own buttons to the top bar so I came up with a new approach that uses PointerWatcher to track cursor position instead. It's been working reliably for me so far, although I haven't had a chance to test on previous versions of GNOME yet.

@jacksongoode: Thanks! Let us know how it goes.

**Comment by jdoe0000000** [comment]
I found that the original approach doesn't work properly with extensions that add their own buttons to the top bar so I came up with a new approach that uses PointerWatcher to track cursor position instead. It's been working reliably for me so far, although I haven't had a chance to test on previous versions of GNOME yet.

@jacksongoode: Thanks! Let us know how it goes.

**Comment by Myned** [comment]
Can confirm the fix works with GNOME 42.0 on X11 Arch without noticeable issues. Much appreciated!

**Comment by jacksongoode** [comment]
Looks good to me! Works fine!

**Comment by tuxor1337** [comment]
Hm, now that this has been fixed upstream (see https://github.com/mlutfy/hidetopbar/issues/354#issuecomment-1091617654), I'm wondering whether it's still worth to merge these changes.

**Comment by Myned** [comment]
Will that upstream fix be backported to older GNOME versions? If not, might be best to use this PR with a version check. 42 has some issues at the moment, so I wouldn't count on others upgrading just yet.

**Comment by tuxor1337** [comment]
I guess, the fix will be in GNOME 42.1 which should supersede 42.0 quite quickly everywhere. Older versions of GNOME are not affected.

**Comment by Myned** [comment]
I had issues with the top bar getting stuck on 41.x for a while (including various UI elements like tooltips on the dash), but I haven't tested older than that.

**Comment by jacksongoode** [comment]
I believe with the latest mutter update (mutter-42.0-5) this issue is fixed - on Fedora 36 beta.

**Comment by Myned** [comment]
I have tested both mutter 42.0-2 and mutter-git (commit [6c8e8fbb](https://gitlab.gnome.org/GNOME/mutter/-/commit/6c8e8fbba45ce881871f478cd65dc8aafe2aef09)) on Arch stable with [hidetopbar](https://extensions.gnome.org/extension/545/hide-top-bar) from the extension store.

The behavior is slightly different for both versions compared to my experiences with older versions of mutter (bar can be unstuck by hovering outside of a window within a small timeframe), but still results in the top bar getting stuck.

This PR continues to fix the issue.

**Comment by Myned** [comment]
Checking in on GNOME 42.3 to confirm that the issue is still only fixed by this PR.

**Comment by tuxor1337** [comment]
I decided to merge this since it seems to fix more than I thought, including #365, #202, and maybe even more legacy issues.

**Pull request merged**
